accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
]

athinaweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('assignments/', include(('assignments.urls', 'assignments'), namespace='assignments')),
    path('about/', TemplateView.as_view(template_name="about.html"), name='about'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('filemanager/', include(('filemanager.urls', 'filemanager'), namespace='filemanager')),
]

filemanager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:inner_path>', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('<str:inner_path>/upload/', views.upload, name='upload'),
    path('<str:inner_path>/view/', views.view_file, name='view_file'),
    path('<str:inner_path>/view/<str:reverse>', views.view_file, name='view_file'),
]

filemanager/models.py
from django.db import models

# Create your models here.

filemanager/forms.py
from django import forms


class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    file_field.required = False

filemanager/views.py
from django.shortcuts import render
from django.conf import settings
import os
from django.contrib.auth.decorators import login_required
from . import utils
from .forms import FileFieldForm
from django.shortcuts import redirect
import datetime
import git


@login_required
def index(request, **kwargs):
    inner_path = kwargs.get('inner_path', None)
    inner_path, inner_path_hyphened, full_path = utils.inner_path_process(inner_path, request.user.id)
    results = []

    # Refresh git repo
    try:
        git.Repo(full_path).remote().pull()
    except git.exc.InvalidGitRepositoryError:  # this fails when navigating to subdirs FIXME: probably
        pass

    files = os.listdir(full_path)
    for file in files:
        if os.path.isfile("%s/%s" % (full_path, file)):
            isfile = True
        else:
            isfile = False
        if inner_path == "":
            path = utils.slashes_encode("%s" % file)
        else:
            path = utils.slashes_encode("%s/%s" % (inner_path, file))
        date_modified = datetime.datetime.fromtimestamp(int(os.path.getmtime("%s/%s" % (full_path, file)))).isoformat()
        if file != ".git":  # hide .git
            results.append({"name": file, "path": path, "isfile": isfile, "date_modified": date_modified})

    previous_dir_path = "|".join(inner_path_hyphened.split("|")[:len(inner_path_hyphened.split("|"))-1])
    if previous_dir_path != "":
        results.append({"name": "..", "path": previous_dir_path, "isfile": False, "date_modified": ""})
    results = sorted(results, key=lambda x: x['isfile'])
    return render(request, 'filemanager/filemanager.html', {"results": results, "inner_path": inner_path,
                                                            "inner_path_hyphened": inner_path_hyphened})


@login_required
def upload(request, **kwargs):
    inner_path = kwargs.get('inner_path', None)
    inner_path, inner_path_hyphened, full_path = utils.inner_path_process(inner_path, request.user.id)
    form = FileFieldForm(request.POST, request.FILES)
    if request.method != "POST":
        return render(request, 'filemanager/upload.html', {"form": form, "inner_path_hyphened": inner_path_hyphened,
                                                           "inner_path": inner_path})
    else:
        files = request.FILES.getlist('file_field')
        # TODO: Prompt for an overwrite question, by default for now we overwrite
        if form.is_valid():
            # Save files on disk
            for file in files:
                with open('%s/%s' % (full_path, file.name), 'wb+') as destination:
                    for chunk in file.chunks():
                        destination.write(chunk)
        if inner_path != "":
            return redirect('filemanager:index', inner_path=inner_path_hyphened)
        else:
            return redirect('filemanager:index')


@login_required
def new_folder(request, **kwargs):
    inner_path = kwargs.get('inner_path', None)
    inner_path, inner_path_hyphened, user_dir = utils.inner_path_process(inner_path, request.user.id)

    return 1


@login_required
def view_file(request, **kwargs):
    inner_path = kwargs.get('inner_path', None)
    inner_path, inner_path_hyphened, full_path = utils.inner_path_process(inner_path, request.user.id)
    with open(full_path, 'rb') as f:
        file_contents = f.read().decode("utf-8")
    reverse_view = kwargs.get('reverse', None)
    if reverse_view == "reverse":
        # TODO: reverse the printing of the view here
        file_contents = "\n".join(reversed(file_contents.split("\n")))
        pass
    return render(request, 'filemanager/view_file.html', {"file_contents": file_contents, "inner_path": inner_path,
                                                          "inner_path_hyphened": inner_path_hyphened})

filemanager/templates/filemanager/filemanager.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block head_addition %}
{% load static %}
<script src='{% static "athinaweb/jquery.min.js" %}'></script>
{% endblock %}

{% block title %}File Manager{% endblock %}


{% block content %}
<div class="mt-2">
<h3><b>Viewing /{{ inner_path }}</b></h3>

<!--
DEPRECATED: No need to upload anything since all assignment dirs are git based
{% include 'filemanager/menu.html' %}

-->

{% if results|length > 0 %}
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Date Modified</th>
        </tr>
        {% for result in results %}
        <tr>
            <td>
                <div class="dir-listing {{ result.isfile|yesno:'isfile,isdir,' }}">
                    {% if result.isfile %}
                    <a href="{% url 'filemanager:view_file' inner_path=result.path %}">{{ result.name }}</a>
                    {% else %}
                    <a href="{% url 'filemanager:index' inner_path=result.path %}">{{ result.name }}</a>
                    {% endif %}
                </div>
            </td>
            <td>{{ result.date_modified }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
There are no files in this folder.
    Try <a href="{% url 'filemanager:upload' inner_path=inner_path_hyphened %}">uploading some</a>.
{% endif %}
</div>
{% endblock %}

filemanager/templates/filemanager/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
            {% if inner_path == '' %}
            <input type="button" class="btn btn-info" value="Upload"
                   onclick="location.href = '{% url 'filemanager:upload' %}';">
            {% else %}
            <input type="button" class="btn btn-info" value="Upload"
                   onclick="location.href = '{% url 'filemanager:upload' inner_path=inner_path_hyphened %}';">
            {% endif %}
</nav>

filemanager/templates/filemanager/upload.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Upload Files{% endblock %}

{% block content %}
<div class="mt-2 form-control">
Uploading to /{{ inner_path }}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary" type="submit">Upload</button>
    <input type="button" class="btn btn-secondary" value="Back"
                   onclick="window.history.back();">
</form>
</div>
{% endblock %}

filemanager/templates/filemanager/view_file.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Viewing {% endblock %}

{% block content %}
<div class="mt-2">
    <h4><b>Viewing /{{ inner_path }}</b></h4>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
            <input type="button" class="btn btn-info" value="Back"
                   onclick="window.history.back();">
    </nav>
    <pre class="pre">
        {{file_contents}}
    </pre>
</div>
{% endblock %}