accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
]

assignments/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', views.assignments, name='assignments'),
    path('new/', views.assignment_create, name='create_assignment'),
    path('<int:assignment_id>/', views.assignment_view, name='assignment_view'),
    path('<int:assignment_id>/log', views.assignment_log, name='assignment_log'),
    path('<int:assignment_id>/edit', views.assignment_create, name='assignment_edit'),
    path('<int:assignment_id>/delete', views.assignment_delete, name='assignment_delete'),
    path('<int:assignment_id>/force/<int:user_id>', views.assignment_force, name='assignment_force'),
    path('api/', views.APIView.as_view(), name="api"),
    path('webhook/', views.push_event, name="webhook"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

athinaweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('assignments/', include(('assignments.urls', 'assignments'), namespace='assignments')),
    path('about/', TemplateView.as_view(template_name="about.html"), name='about'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('filemanager/', include(('filemanager.urls', 'filemanager'), namespace='filemanager')),
]

filemanager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:inner_path>', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('<str:inner_path>/upload/', views.upload, name='upload'),
    path('<str:inner_path>/view/', views.view_file, name='view_file'),
    path('<str:inner_path>/view/<str:reverse>', views.view_file, name='view_file'),
]

assignments/models.py
from django.db import models
from django.utils import timezone


class Assignment(models.Model):
    name = models.CharField(max_length=200, unique=True)
    absolute_path = models.CharField(max_length=200, editable=False)
    owner = models.IntegerField(editable=False, default=1)
    date_created = models.DateTimeField('Date Created', default=timezone.now, editable=False)
    data_updated = models.DateTimeField('Date Updated', auto_now=True)
    active = models.BooleanField(default=True)
    simulate = models.BooleanField(default=False)
    git_source = models.CharField(max_length=255, default="")
    git_username = models.CharField(max_length=255, default="", blank=True)
    git_password = models.CharField(max_length=255, default="", blank=True,
                                    help_text="Use an access token and not your real password.")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        keep_characters = (' ', '.', '_', '-')
        self.name = "".join(c for c in self.name if c.isalnum() or c in keep_characters).rstrip()
        super(Assignment, self).save(*args, **kwargs)

assignments/forms.py
from django import forms
from .models import Assignment


class AssignmentForm(forms.ModelForm):

    class Meta:
        model = Assignment
        fields = ('name', 'active', "git_source", "git_username", "git_password")

assignments/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Assignment
from .forms import AssignmentForm
import os
import shutil
from rest_framework import generics
from .serializers import AssignmentListSerializer
import git
import html
import base64
import re
import glob
import pymysql
import yaml
import json
from datetime import timedelta
import dateutil.parser
from athinaweb.athina_db import db_info


@login_required()
def index(request):
    assignments(request)


@login_required
def assignments(request):
    # TODO: incorporate paginator: https://docs.djangoproject.com/en/2.0/topics/pagination/
    # TODO: on delete should prompt a question that verifies by typing the name of the thing to be deleted
    assignments_list = Assignment.objects.filter(owner=request.user.id).order_by('-active', 'name')
    return render(request, 'assignments/assignments.html',
                  {"assignments": assignments_list,
                   'assignments_len': len(assignments_list)})


@login_required
def assignment_create(request, **kwargs):
    """ View for creating and editing model Assignment using Assignment Form"""
    if request.method == "POST":
        assignment_id = kwargs.get('assignment_id', None)
        if assignment_id is not None:
            assignment = get_object_or_404(Assignment, pk=assignment_id)
            if assignment.owner != request.user.id:
                raise Http404
            form = AssignmentForm(request.POST, instance=assignment)
        else:
            form = AssignmentForm(request.POST)
        if form.is_valid():
            if form.instance.pk is None:  # New assignment, create folder
                assignment = form.save(commit=False)
                assignment.owner = request.user.id
                assignment.save()  # we have to save in order to get the pk
                assignment.absolute_path = "%s/%s/%s" % (settings.MEDIA_ROOT, request.user.id, assignment.name)
                assignment.save()
                if not os.path.exists(assignment.absolute_path):
                    os.makedirs(assignment.absolute_path)
                if assignment.git_password != "":
                    url_matches = re.findall("(.*?)://(.*?)$", assignment.git_source)
                    if url_matches[0][0] == 'https':
                        git_url = "%s://%s:%s@%s" % (url_matches[0][0],
                                                         html.escape(assignment.git_username),
                                                         html.escape(assignment.git_password),
                                                         url_matches[0][1])
                        git.Repo.clone_from(git_url, assignment.absolute_path)
                    else:
                        git.Repo.clone_from(assignment.git_source, assignment.absolute_path)
                else:
                    git.Repo.clone_from(assignment.git_source, assignment.absolute_path)
            else:  # Existing assignment, move folder
                old_assignment = get_object_or_404(Assignment, pk=assignment_id)
                assignment = form.save(commit=False)
                if old_assignment.name != assignment.name:
                    assignment.absolute_path = "%s/%s/%s" % (settings.MEDIA_ROOT, request.user.id, assignment.name)
                    shutil.move("%s/%s" % (settings.BASE_DIR, old_assignment.absolute_path),
                                "%s/%s" % (settings.BASE_DIR, assignment.absolute_path))
                assignment.save()
            os.chmod("%s/%s" % (settings.BASE_DIR, assignment.absolute_path), 0o777)
            return redirect('filemanager:index', inner_path="%s" % assignment.name)
    else:
        assignment_id = kwargs.get('assignment_id', None)
        if assignment_id is not None:
            assignment = get_object_or_404(Assignment, pk=assignment_id)
            if assignment.owner != request.user.id:
                raise Http404
            form = AssignmentForm(instance=assignment)
        else:
            form = AssignmentForm()
    return render(request, 'assignments/assignment_create.html', {'form': form})


@login_required
def assignment_log(request, assignment_id):
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    if assignment.owner != request.user.id:
        raise Http404
    else:
        list_of_files = glob.glob('%s/%s/*.log' % (settings.BASE_DIR, assignment.absolute_path))
        try:
            latest_file = os.path.basename(max(list_of_files, key=os.path.getctime))
        except ValueError:
            raise Http404
        return redirect('filemanager:view_file', inner_path="%s%s%s" % (assignment.name, "|", latest_file))


@login_required
def assignment_view(request, assignment_id):
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    if assignment.owner != request.user.id:
        raise Http404
    else:
        # Security check passed
        conn = connect_to_db()
        cur = conn.cursor()
        # Get moss url (if it exists)
        course_id, assignment_id = get_course_assignment_id(request, assignment.absolute_path)
        cur.execute('SELECT variable_value FROM assignmentdata WHERE variable = %s AND '
                    'course_id = %s AND assignment_id = %s',
                    ('moss_url', course_id, assignment_id,))
        moss_url = cur.fetchone() if cur.fetchone() is not None else '#'

        cur.execute('SELECT user_id, user_fullname, secondary_id, repository_url, commit_date, last_graded,'
                    'last_grade, last_report, moss_max, moss_average, force_test, tester_active FROM users WHERE '
                    '`course_id` = %s AND `assignment_id` = %s', (course_id, assignment_id,))
        users = []
        for user in cur.fetchall():
            if user[3] is None and user[6] is None:
                color = "table-danger"
                info = "No repository url submitted"
            elif user[10] == 1:
                color = "table-warning"
                info = "Forced test scheduled"
            elif user[11] == 1:
                color = "table-warning"
                info = "Testing in progress"
            elif user[4] < user[5]:
                # graded
                color = "table-success"
                info = "Graded"
            else:
                # not grade or no url
                color = "table-warning"
                info = "Assignment not graded yet or past due date"
            users.append((user[0], user[1], user[2], color, info, user[6],
                          base64.b64encode(user[7]).decode("ascii"), user[8], user[9]))
        conn.close()
    return render(request, 'assignments/assignment_view.html', {"users": users, "users_len": len(users),
                                                                "assignment": assignment, "moss_url": moss_url})


def connect_to_db():
    db_details = db_info()
    return pymysql.connect(host=db_details.athina_mysql_host, user=db_details.athina_mysql_username,
                           password=db_details.athina_mysql_password, port=int(db_details.athina_mysql_port),
                           db="athina")


@login_required
def assignment_delete(request, assignment_id):
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    if assignment.owner != request.user.id:
        raise Http404
    try:
        shutil.rmtree("%s/%s" % (settings.BASE_DIR, assignment.absolute_path))
    except FileNotFoundError:  # this error wont affect functionality
        pass
    assignment.delete()
    return redirect('assignments:assignments')


@login_required
def get_course_assignment_id(request, absolute_path):
    with open('%s/%s/athina.yaml' % (settings.BASE_DIR, absolute_path), 'r') as stream:
        yaml_dict = yaml.load(stream, Loader=yaml.SafeLoader)
    return yaml_dict['course_id'], yaml_dict['assignment_id']


@login_required
def assignment_force(request, assignment_id, user_id):
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    if assignment.owner != request.user.id:
        raise Http404
    else:
        # Revert the commit date on record to some older version. This will force Athina to think that it didn't check
        # the current commit. Also revert last_graded to an earlier date
        conn = connect_to_db()
        cur = conn.cursor()
        course_id, assignment_id = get_course_assignment_id(request, assignment.absolute_path)
        cur.execute("SELECT repository_url FROM users WHERE user_id=%s AND course_id=%s AND assignment_id=%s LIMIT 1",
                    (user_id, course_id, assignment_id,))
        result = cur.fetchone()
        repository_url = result[0]
        if repository_url is not None or "":
            cur.execute("UPDATE users SET force_test=1 WHERE course_id=%s AND assignment_id=%s AND repository_url=%s",
                        (course_id, assignment_id, repository_url,))
        else:
            cur.execute("UPDATE users SET force_test=1 WHERE course_id=%s AND assignment_id=%s AND user_id=%s",
                        (course_id, assignment_id, user_id,))
        conn.commit()
        conn.close()
        return redirect('assignments:assignment_view', assignment_id=assignment.pk)


@csrf_exempt
def push_event(request):
    if request.headers.get('X-Gitlab-Event', '') == 'Push Hook':
        try:
            json_body = json.loads(request.body)
            student_git_url = json_body['project']['git_http_url']
        except KeyError:
            return HttpResponse('ok')
        webhook_token = request.headers.get('X-Gitlab-Token', '')
        conn = connect_to_db()
        cur = conn.cursor()

assignments/templates/assignments/assignment_create.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Create/Edit Assignment{% endblock %}

{% block content %}
<div class="mt-2 form-control">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Save</button>
        <input type="button" class="btn btn-secondary" value="Back"
                   onclick="window.history.back();">
    </form>
</div>
{% endblock %}

assignments/templates/assignments/assignment_view.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}View Assignment{% endblock %}

{% block content %}
<div class="mt-2">
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
</nav>


    {% if users_len > 0 %}
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>Secondary ID</th>
                <th>Info</th>
                <th>Grade</th>
                <th>Moss Max/Avg Similarity</th>
                <th>Options</th>
            </tr>
            {% for user in users %}
            <tr class="{{ user.3 }}">
                <td>
                    {{ user.1 }}
                </td>
                <td>{{ user.2 }}</td>
                <td>{{ user.4 }}</td>
                <td>{{ user.5 }}</td>
                <td>{{ user.9 }} / {{ user.10 }}</td>
                <td>
                    <input type="button" class="btn btn-info" value="Test Report"
                    onclick="location.href = 'data:application/octet-stream;charset=utf-8;base64,{{ user.6 }}';">
                    <input type="button" class="btn btn-info" value="Moss Report"
                    onclick="location.href = '{{ moss_url }}';">
                    <input type="button" class="btn btn-warning" value="Force Rerun"
                    onclick="location.href = '{% url 'assignments:assignment_force' assignment_id=assignment.pk  user_id=user.0  %}';">
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    There are no assignments in your account. Try <a href="{% url 'assignments:create_assignment' %}">creating on</a>.
    {% endif %}
</div>
{% endblock %}

assignments/templates/assignments/assignments.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block head_addition %}
{% load static %}
<script src='{% static "athinaweb/jquery.min.js" %}'></script>
{% endblock %}

{% block title %}Assignments{% endblock %}

{% block content %}
<div class="mt-2">
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
<input type="button" class="btn btn-info" value="New Assignment"
                   onclick="location.href = '{% url 'assignments:create_assignment' %}';">
</nav>


    {% if assignments_len > 0 %}
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>Options</th>
            </tr>
            {% for assignment in assignments %}
                {% if assignment.active is True %}
                    <tr class="table-success">
                {% else %}
                    <tr class="table-danger">
                {% endif %}
                <td><a href="{% url 'assignments:assignment_view' assignment_id=assignment.pk %}">
                    {{ assignment.name }}
                </a></td>
                <td>
                    <input type="button" class="btn btn-info" value="View Users"
                    onclick="location.href = '{% url 'assignments:assignment_view' assignment_id=assignment.pk %}';">
                    <input type="button" class="btn btn-info" value="View Dir"
                    onclick="location.href = '{% url 'filemanager:index' inner_path=assignment.name %}';">
                    <input type="button" class="btn btn-info" value="View Log"
                    onclick="location.href = '{% url 'assignments:assignment_log' assignment_id=assignment.pk %}';">
                    <input type="button" class="btn btn-warning" value="Edit"
                    onclick="location.href = '{% url 'assignments:assignment_edit' assignment_id=assignment.pk %}';">
                    <a class="confirm-delete{{ assignment.id }} btn btn-danger"
                       href="{% url 'assignments:assignment_delete' assignment_id=assignment.pk %}">Delete</a></td>
                <script>
            $('.confirm-delete{{ assignment.id }}').click(function(){
                return confirm("Are you sure you want to delete?");
            })
                </script>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    There are no assignments in your account. Try <a href="{% url 'assignments:create_assignment' %}">creating one</a>.
    {% endif %}
</div>
{% endblock %}