accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
]

assignments/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', views.assignments, name='assignments'),
    path('new/', views.assignment_create, name='create_assignment'),
    path('<int:assignment_id>/', views.assignment_view, name='assignment_view'),
    path('<int:assignment_id>/log', views.assignment_log, name='assignment_log'),
    path('<int:assignment_id>/edit', views.assignment_create, name='assignment_edit'),
    path('<int:assignment_id>/delete', views.assignment_delete, name='assignment_delete'),
    path('<int:assignment_id>/force/<int:user_id>', views.assignment_force, name='assignment_force'),
    path('api/', views.APIView.as_view(), name="api"),
    path('webhook/', views.push_event, name="webhook"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

athinaweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('assignments/', include(('assignments.urls', 'assignments'), namespace='assignments')),
    path('about/', TemplateView.as_view(template_name="about.html"), name='about'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('filemanager/', include(('filemanager.urls', 'filemanager'), namespace='filemanager')),
]

templates/about.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<div class="mt-2">
<h3><b>About</b></h3>
<hr>

<p>For a full list of contributors and additional information please visit:
    <a href="https://github.com/athina-edu/">Athina Github Organisation</a>
</p>

    <p>Contributions to the project are more than welcome!
        Also, feel free to share your assignment tests and configuration with others</p>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Athina Web UI{% endblock %}</title>
    {% block head_addition %}{% endblock %}
    {% load static %}
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Font Awesome css -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href='{% static "athinaweb/base.css" %}'>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Athina Web</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if not user.is_authenticated %}
            <li class="nav-item {% if request.get_full_path == '/' %}active{% endif %}">
                <a class="nav-link" href="/">Home</a>
            </li>
            {% endif %}

            {% url 'assignments:assignments' as assignments_url %}
            <li class="nav-item {% if  request.get_full_path == assignments_url %}active{% endif %}">
                <a class="nav-link" href="{{ assignments_url }}">Assignments</a>
            </li>
            <li class="nav-item {% if  request.get_full_path == '/about/' %}active{% endif %}">
                <a class="nav-link" href="/about">About</a>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% block loginblock %}
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link disabled"><span class="fa fa-user"></span> {{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}"><span class="fa fa-sign-out"></span> Logout</a>
            </li>
            {% else %}
            <!-- <li class="nav-item">
                <a class="nav-link" href="{% url 'django_registration_register' %}"><span class="fa fa-user"></span> Sign Up</a>
            </li> -->
            <li>
                <a class="nav-link" href="{% url 'login' %}"><span class="fa fa-sign-in"></span> Login</a>
            </li>
            {% endif %}
            {% endblock %}

        </ul>
    </div>
</nav>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-1"></div>

        <div class="col-lg-10">
            {% block content %}
            {% endblock %}
        </div>

        <div class="col-lg-1"></div>
    </div>
</div>

</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="mt-2">
<h3><b>Welcome</b></h3>
<hr>

<p>Athina is a formative assessment tool for programming assignments and this is its Web Interface.</p>

<p>Through this interface you can manage assignments for multiple courses by creating assignments and uploading
    configuration and test files among other things.</p>

<p>Any bugs or features requests can be send to: Michael.Tsikerdekis(at)wwu.edu</p>

<p>If you need an account on this installation, contact the individual that set this server up.</p>
</div>
{% endblock %}

templates/signup.html
<!-- DEPRECATED, left here fore reference -->
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}